// @vitest-environment node
//
// jsdom's Request/FormData/Blob shims don't produce a real streamable
// multipart body (see attachments-pipeline.test.ts) — this file drives
// the real route handlers with a real multipart upload, so it needs
// Node's real fetch primitives.
import { randomUUID } from "node:crypto";
import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { NextRequest } from "next/server";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { prisma } from "@/server/db";
import { config } from "@/server/config";
import { createSession, SESSION_COOKIE_NAME } from "@/modules/auth/session";
import {
  GET as getCertificateRoute,
  POST as uploadCertificateRoute,
} from "@/app/api/v1/admin/certificate/route";
import { bootstrapSystemData } from "../../prisma/lib/bootstrap-system-data";

const execFileAsync = promisify(execFile);

/**
 * Administration -> TLS Certificate, API.md's `GET/POST
 * /api/v1/admin/certificate` — exercised as real route handlers against
 * a real keystore generated by `keytool` (a dev/test-only tool; the
 * runtime itself never shells out to it — see src/modules/certificates/jks.ts).
 */

const CSRF_TOKEN = "test-csrf-token";
const KEYSTORE_PASSWORD = "keystorepass123";
const createdUserIds: string[] = [];
let certDir: string;
let validJksBuffer: Buffer;

beforeAll(async () => {
  // CERTIFICATE_MANAGE is a newly added permission — the shared test
  // database's ADMIN role only has it once bootstrap re-runs (upserts are
  // additive, so this is safe alongside every other test file's own data).
  await bootstrapSystemData(prisma);

  certDir = await mkdtemp(path.join(tmpdir(), "ca-cert-test-"));
  config.TLS_CERT_DIR = certDir;

  const jksPath = path.join(certDir, "source.jks");
  await execFileAsync("keytool", [
    "-genkeypair",
    "-alias",
    "servercert",
    "-keyalg",
    "RSA",
    "-keysize",
    "2048",
    "-validity",
    "365",
    "-keystore",
    jksPath,
    "-storepass",
    KEYSTORE_PASSWORD,
    "-keypass",
    KEYSTORE_PASSWORD,
    "-dname",
    "CN=cert-test.local, OU=IT, O=Test, L=City, ST=State, C=US",
  ]);
  validJksBuffer = await readFile(jksPath);
});

afterAll(async () => {
  if (createdUserIds.length) {
    await prisma.user.deleteMany({ where: { id: { in: createdUserIds } } });
  }
  await rm(certDir, { recursive: true, force: true });
  await prisma.$disconnect();
});

async function makeAuthedUser(
  displayName: string,
  roleKey: "ADMIN" | "EMPLOYEE",
) {
  const user = await prisma.user.create({
    data: {
      email: `cert-test-${randomUUID()}@editortest.local`,
      displayName,
      firstName: displayName,
      lastName: "Test",
      authProvider: "LOCAL",
      passwordHash: "argon2id$fake$hash$for$testing",
    },
  });
  createdUserIds.push(user.id);

  const role = await prisma.role.findUniqueOrThrow({ where: { key: roleKey } });
  await prisma.userRole.create({ data: { userId: user.id, roleId: role.id } });

  const { cookieValue } = await createSession({
    userId: user.id,
    authProvider: "LOCAL",
  });
  return { user, cookieValue };
}

function baseHeaders(cookieValue: string) {
  return {
    origin: config.APP_URL,
    cookie: `${SESSION_COOKIE_NAME}=${cookieValue}; ${config.CSRF_COOKIE_NAME}=${CSRF_TOKEN}`,
    "x-csrf-token": CSRF_TOKEN,
  };
}

function buildGetRequest(cookieValue: string) {
  return new NextRequest("http://localhost:3000/api/v1/admin/certificate", {
    method: "GET",
    headers: new Headers(baseHeaders(cookieValue)),
  });
}

function buildUploadRequest(options: {
  cookieValue: string;
  fileBuffer: Buffer;
  keystorePassword: string;
  keyPassword?: string;
}) {
  const formData = new FormData();
  formData.append(
    "file",
    new Blob([new Uint8Array(options.fileBuffer)]),
    "certificate.jks",
  );
  formData.append("keystorePassword", options.keystorePassword);
  if (options.keyPassword) formData.append("keyPassword", options.keyPassword);
  return new NextRequest("http://localhost:3000/api/v1/admin/certificate", {
    method: "POST",
    headers: new Headers(baseHeaders(options.cookieValue)),
    body: formData,
  });
}

describe("GET /api/v1/admin/certificate", () => {
  it("403s a user without CERTIFICATE_MANAGE", async () => {
    const { cookieValue } = await makeAuthedUser("Cert Reader", "EMPLOYEE");
    const response = await getCertificateRoute(buildGetRequest(cookieValue));
    expect(response.status).toBe(403);
  });

  it("reports the placeholder self-signed certificate as present", async () => {
    // install.sh always writes one before an admin ever reaches this
    // screen — simulate that here rather than depending on test order.
    await execFileAsync("openssl", [
      "req",
      "-x509",
      "-nodes",
      "-newkey",
      "rsa:2048",
      "-days",
      "90",
      "-keyout",
      path.join(certDir, "server.key"),
      "-out",
      path.join(certDir, "server.crt"),
      "-subj",
      "/CN=placeholder.local",
    ]);

    const { cookieValue } = await makeAuthedUser("Cert Reader 2", "ADMIN");
    const response = await getCertificateRoute(buildGetRequest(cookieValue));
    expect(response.status).toBe(200);
    const info = (await response.json()).data;
    expect(info.present).toBe(true);
    expect(info.isSelfSigned).toBe(true);
    expect(info.subject).toContain("placeholder.local");
  });
});

describe("POST /api/v1/admin/certificate", () => {
  it("403s a user without CERTIFICATE_MANAGE", async () => {
    const { cookieValue } = await makeAuthedUser(
      "Cert Uploader Denied",
      "EMPLOYEE",
    );
    const response = await uploadCertificateRoute(
      buildUploadRequest({
        cookieValue,
        fileBuffer: validJksBuffer,
        keystorePassword: KEYSTORE_PASSWORD,
      }),
    );
    expect(response.status).toBe(403);
  });

  it("replaces the certificate, writes an audit entry, and GET reflects it", async () => {
    const { user, cookieValue } = await makeAuthedUser(
      "Cert Uploader",
      "ADMIN",
    );
    const response = await uploadCertificateRoute(
      buildUploadRequest({
        cookieValue,
        fileBuffer: validJksBuffer,
        keystorePassword: KEYSTORE_PASSWORD,
      }),
    );
    expect(response.status).toBe(200);
    const info = (await response.json()).data;
    expect(info.present).toBe(true);
    expect(info.subject).toContain("cert-test.local");
    expect(info.isSelfSigned).toBe(true);
    expect(info.lastUploadedBy).toBe(user.email);

    const onDisk = await readFile(path.join(certDir, "server.crt"), "utf8");
    expect(onDisk).toContain("BEGIN CERTIFICATE");

    const audit = await prisma.auditLog.findFirst({
      where: { action: "TLS_CERTIFICATE_UPLOADED", actorId: user.id },
      orderBy: { createdAt: "desc" },
    });
    expect(audit).not.toBeNull();

    const getResponse = await getCertificateRoute(buildGetRequest(cookieValue));
    const getInfo = (await getResponse.json()).data;
    expect(getInfo.subject).toContain("cert-test.local");
  });

  it("422s a wrong keystore password without touching the certificate on disk", async () => {
    const { cookieValue } = await makeAuthedUser(
      "Cert Uploader Bad Password",
      "ADMIN",
    );
    const before = await readFile(path.join(certDir, "server.crt"), "utf8");

    const response = await uploadCertificateRoute(
      buildUploadRequest({
        cookieValue,
        fileBuffer: validJksBuffer,
        keystorePassword: "definitely-wrong",
      }),
    );
    expect(response.status).toBe(422);

    const after = await readFile(path.join(certDir, "server.crt"), "utf8");
    expect(after).toBe(before);
  });

  it("422s a keystore with an already-expired certificate", async () => {
    const expiredPath = path.join(certDir, "expired.jks");
    await execFileAsync("keytool", [
      "-genkeypair",
      "-alias",
      "servercert",
      "-keyalg",
      "RSA",
      "-keysize",
      "2048",
      "-startdate",
      "-400d",
      "-validity",
      "1",
      "-keystore",
      expiredPath,
      "-storepass",
      KEYSTORE_PASSWORD,
      "-keypass",
      KEYSTORE_PASSWORD,
      "-dname",
      "CN=expired.local",
    ]);
    const expiredBuffer = await readFile(expiredPath);

    const { cookieValue } = await makeAuthedUser(
      "Cert Uploader Expired",
      "ADMIN",
    );
    const response = await uploadCertificateRoute(
      buildUploadRequest({
        cookieValue,
        fileBuffer: expiredBuffer,
        keystorePassword: KEYSTORE_PASSWORD,
      }),
    );
    expect(response.status).toBe(422);
    const error = (await response.json()).error;
    expect(error.message).toMatch(/expired/i);
  });

  it("422s a garbage (non-keystore) file", async () => {
    const { cookieValue } = await makeAuthedUser(
      "Cert Uploader Garbage",
      "ADMIN",
    );
    const response = await uploadCertificateRoute(
      buildUploadRequest({
        cookieValue,
        fileBuffer: Buffer.from("not a keystore at all"),
        keystorePassword: "whatever",
      }),
    );
    expect(response.status).toBe(422);
  });
});
