-- AlterTable
-- Note: this migration was generated by `prisma migrate dev --create-only`,
-- which also proposed dropping post_search_vector_idx and
-- user_display_name_trgm_idx. Those are raw-SQL GIN/trigram indexes added
-- in the init migration (not expressible as a Prisma @@index), so Prisma's
-- schema diff doesn't see them and wrongly treats them as drift. Removed
-- from this migration — see prisma/migrations/20260905094359_init.
ALTER TABLE "Post" ADD COLUMN     "draftAttachmentIds" JSONB;
